version: 2
jobs:
  build:
    working_directory: /go/src/github.com/favclip/testerator
    docker:
      - image: vvakame/circleci-gaego
        environment:
          GO111MODULE: "on"
          DATASTORE_EMULATOR_HOST: "localhost:8081"
          DATASTORE_PROJECT_ID:    "unittest"
      - image: google/cloud-sdk:295.0.0
        command: ['gcloud', '--project=unittest', 'beta', 'emulators', 'datastore', 'start', '--host-port=localhost:8081', '--no-store-on-disk', '--consistency=1.0']

    steps:
      - checkout
      - run:
          name: run GAE/Go test
          command: go test -v ./...
